# Generated by Django 5.0.2 on 2024-03-22 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_number', models.AutoField(help_text='Enter category id', primary_key=True, serialize=False)),
                ('category_name', models.CharField(help_text='Enter category name', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Card',
            fields=[
                ('card_number', models.CharField(help_text='Enter customer card number', max_length=13, primary_key=True, serialize=False)),
                ('cust_surname', models.CharField(help_text='Enter customer surname', max_length=50)),
                ('cust_name', models.CharField(help_text='Enter customer name', max_length=50)),
                ('cust_patronymic', models.CharField(help_text='Enter customer patronymic', max_length=50, null=True)),
                ('phone_number', models.CharField(help_text='Enter customer phone number', max_length=13)),
                ('city', models.CharField(help_text='Enter customer city', max_length=50, null=True)),
                ('street', models.CharField(help_text='Enter customer street', max_length=50, null=True)),
                ('zip_code', models.CharField(help_text='Enter customer zip code', max_length=9, null=True)),
                ('percent', models.IntegerField(help_text='Enter customer discount')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id_employee', models.CharField(help_text='Enter employee id', max_length=10, primary_key=True, serialize=False)),
                ('empl_surname', models.CharField(help_text='Enter employee surname', max_length=50)),
                ('empl_name', models.CharField(help_text='Enter employee name', max_length=50)),
                ('empl_patronymic', models.CharField(help_text='Enter employee patronymic', max_length=50, null=True)),
                ('empl_role', models.CharField(help_text='Enter employee role', max_length=10)),
                ('salary', models.DecimalField(decimal_places=4, help_text='Enter employee salary', max_digits=14)),
                ('date_of_birth', models.DateField(help_text='Enter employee date of birth')),
                ('date_of_start', models.DateField(help_text='Enter date of employee work started')),
                ('phone_number', models.CharField(help_text='Enter employee phone_number', max_length=13)),
                ('city', models.CharField(help_text='Enter employee city', max_length=50)),
                ('street', models.CharField(help_text='Enter employee street', max_length=50)),
                ('zip_code', models.CharField(help_text='Enter employee zip code', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('check_number', models.CharField(help_text="Enter receipt's number", max_length=10, primary_key=True, serialize=False)),
                ('print_date', models.DateTimeField(help_text="Enter receipt's print date")),
                ('sum_total', models.DecimalField(decimal_places=4, help_text="Enter receipt's total sum", max_digits=13)),
                ('vat', models.DecimalField(decimal_places=4, help_text="Enter receipt's vat", max_digits=13)),
                ('card_number', models.ForeignKey(help_text='Enter card number associated with receipt', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receipts', to='store.customer_card')),
                ('id_employee', models.ForeignKey(help_text='Enter id of employee who issued receipt', on_delete=django.db.models.deletion.DO_NOTHING, related_name='receipts', to='store.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(help_text='Enter product id', primary_key=True, serialize=False)),
                ('product_name', models.CharField(help_text='Enter product name', max_length=50)),
                ('characteristics', models.TextField(help_text='Enter product characteristics', max_length=100)),
                ('category_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='Store_Product',
            fields=[
                ('UPC', models.CharField(help_text="Enter store product's UPC", max_length=12, primary_key=True, serialize=False)),
                ('selling_price', models.DecimalField(decimal_places=4, help_text="Enter store product's price", max_digits=13)),
                ('products_number', models.IntegerField(help_text='Enter number of store products')),
                ('promotional_product', models.BooleanField(help_text='Is store product on discount')),
                ('UPC_prom', models.ForeignKey(help_text="Enter store product's promotion UPC", null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.store_product')),
                ('id_product', models.ForeignKey(help_text="Enter store product's id", on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.IntegerField(help_text='Enter number of units sold')),
                ('selling_price', models.DecimalField(decimal_places=4, help_text='Enter selling price per unit', max_digits=13)),
                ('check_number', models.ForeignKey(help_text='Enter number of receipt', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.check')),
                ('UPC', models.ForeignKey(help_text="Enter product's UPC", on_delete=django.db.models.deletion.DO_NOTHING, related_name='sold', to='store.store_product')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('UPC', 'check_number'), name='composite_primary_key'),
        ),
    ]
