# Generated by Django 5.0.2 on 2024-03-22 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sale',
            name='composite_primary_key',
        ),
    ]
